language: node_js

node_js:
  - "8.9.1"

services:
  - mongodb

cache:
  directories:
  - node_modules

git:
  depth: 3

script:
  - yarn test:check-coverage

after_script:
  - yarn report-coverage

env:
  global:
    - JWT_SECRET=0a6b944d-d2fb-46fc-a85e-0295c986cd9f
    - MONGO_HOST=mongodb://localhost
